### ISSUE TITLE
"Affix" component appears Issue when using the "target" property.

### ISSUE THREAD

**Issue by Shadowzzh** [ecaps1038/yike-design-react#28]
- target document link：https://react.yike.design/components/affix#%E6%8C%87%E5%AE%9A%E5%AE%B9%E5%99%A8%E6%BB%9A%E5%8A%A8

- descritiopn：当使用 target 属性时。在 target 內一直滚动，触发 “affixing“。再把鼠标移动出 “target”，在 Window 內滚动，内容会从 target 中跑出去。如图；

<img width="1425" alt="image" src="https://github.com/ecaps1038/yike-design-react/assets/27343063/119a6ce4-861e-420e-8b5d-7193e5e47910" />

- possible reason：childlren 被设置为 position:fixed 时，target 的 position 没有被设置为 relative。

**Comment by xiefenga** [comment]
确实有这个问题，之前是参照antd4实现的，antd4也有这样的问题。
还没时间修，欢迎提PR修复

**Comment by Shadowzzh** [comment]
可以请教一下 useNormalizedContainer 钩子的作用么。
我虽然能看懂它的运行方式，但是没搞明白它的具体作用。
谢谢。

**Comment by xiefenga** [comment]
有点忘了，我大致看了一下，应该主要是提供对target属性保持引用，例如 

```tsx
<Affix target={() => targetRef.current}>
  <Button>Affix top 10px in container</Button>
</Affix>
```
如果用到 Affix 组件的组件发生了更新，target 属性每次都会更新，但其实 targetRef.current 不一定改变了，就会导致一直 Affix 重复的更新
